version: '3.9'
services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn rest_api:app --host 0.0.0.0 --port 8000 --reload
  streamlit:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
